export function generateReportHTML(data: {
  studentName?: string;
  date: string;
  type: "descriptive" | "omr";
  result: Record<string, unknown>;
  analysis?: string;
}): string {
  const { studentName, date, type, result, analysis } = data;

  const rawSteps =
    (result.steps as Array<Record<string, unknown>>) ||
    (result.stepGrades as Array<Record<string, unknown>>) ||
    [];

  const stepsHTML = rawSteps
    .map((s) => {
      const name = s.step_name ?? s.topic ?? s.rubricId ?? "";
      const awarded = s.marks_awarded ?? s.awarded ?? 0;
      const max = s.max_marks ?? s.max ?? 0;
      const feedback = s.feedback ?? s.note ?? "";

      let evidence = s.evidence_quote ?? "";
      if (!evidence && Array.isArray(s.citations) && s.citations.length > 0) {
        evidence = s.citations[0].excerpt ?? s.citations[0].text ?? "";
      }

      return `
    <tr>
      <td>${name}</td>
      <td>${awarded} / ${max}</td>
      <td style="font-style:italic;color:#555">${evidence ? `"${evidence}"` : "N/A"}</td>
      <td>${feedback}</td>
    </tr>`;
    })
    .join("");

  const totalMarks = result.total_marks ?? result.score ?? 0;
  const maxMarks = result.max_marks ?? result.total ?? 100;
  const overallFeedback = result.overall_feedback ?? result.summary ?? "";
  const confidenceScore =
    (result.confidence_score as number) ?? (result.confidence as number);
  const isFallback = Boolean(result.fallback || result.warning);

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <title>PrepForge Report — ${studentName ?? "Student"}</title>
  <style>
    @media print { body { margin: 0; } .no-print { display: none; } }
    body { font-family: 'Segoe UI', Arial, sans-serif; padding: 32px; color: #111; max-width: 900px; margin: 0 auto; }
    h1 { color: #1a1a2e; border-bottom: 2px solid #4f46e5; padding-bottom: 8px; }
    .meta { display: flex; gap: 32px; margin: 16px 0; font-size: 14px; color: #444; flex-wrap: wrap; }
    .score-box { background: #f0f4ff; border: 1px solid #c7d2fe; border-radius: 8px; padding: 16px; margin: 16px 0; }
    .score-box h2 { margin: 0 0 4px; font-size: 28px; color: #4f46e5; }
    table { width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 13px; }
    th { background: #4f46e5; color: white; padding: 8px 12px; text-align: left; }
    td { padding: 8px 12px; border-bottom: 1px solid #e5e7eb; vertical-align: top; }
    tr:nth-child(even) td { background: #f9fafb; }
    .analysis { margin-top: 24px; background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 16px; }
    .analysis h3 { color: #166534; margin-top: 0; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 12px; }
    .badge-ok { background: #dcfce7; color: #166534; }
    .badge-warn { background: #fef9c3; color: #854d0e; }
    .confidence { font-size: 13px; color: #6b7280; margin-top: 8px; }
    .footer { margin-top: 32px; text-align: center; font-size: 11px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 16px; }
  </style>
</head>
<body>
  <h1>PrepForge Evaluation Report</h1>
  <div class="meta">
    <span><strong>Student:</strong> ${studentName ?? "N/A"}</span>
    <span><strong>Date:</strong> ${date}</span>
    <span><strong>Type:</strong> ${type === "descriptive" ? "Descriptive" : "OMR"}</span>
    ${isFallback ? '<span class="badge badge-warn">Offline mode</span>' : '<span class="badge badge-ok">AI graded</span>'}
  </div>

  <div class="score-box">
    <h2>${totalMarks} / ${maxMarks}</h2>
    <div>${overallFeedback}</div>
    ${confidenceScore !== undefined ? `<div class="confidence">AI Confidence: ${(confidenceScore * 100).toFixed(0)}%</div>` : ""}
  </div>

  ${
    stepsHTML
      ? `
  <h3>Step-by-Step Breakdown</h3>
  <table>
    <thead><tr><th>Step</th><th>Marks</th><th>Evidence</th><th>Feedback</th></tr></thead>
    <tbody>${stepsHTML}</tbody>
  </table>`
      : ""
  }

  ${
    analysis
      ? `
  <div class="analysis">
    <h3>Strengths & Gaps Analysis</h3>
    <pre style="white-space:pre-wrap;font-family:inherit">${analysis}</pre>
  </div>`
      : ""
  }

  <div class="no-print" style="margin-top:32px;text-align:center">
    <button onclick="window.print()" style="padding:10px 24px;background:#4f46e5;color:white;border:none;border-radius:6px;cursor:pointer;font-size:15px">
      Download PDF
    </button>
  </div>

  <div class="footer">
    Generated by PrepForge — Faculty Evaluation AI &middot; ${date}
  </div>
</body>
</html>`;
}
